vie-en-yoga/vie-en-yoga.github.io

- CNAME
- cours/contenu.html
Changelog:
1. Add `CNAME` file mentioning `www.vie-en-yoga.com`
2. Update DNS records. (Done separately from this PR in OVH portal.)
Before:
```
www         IN A      213.186.33.82
```
After:
```
www         IN CNAME vie-en-yoga.github.io
```
3. Update links previously pointing to the files hosting behind `vie-en-yoga.com`.
> Configure vie-en-yoga.com domain name

- cours/index.html
- stages.html
Rajouté le lien sur Thomas Delavenne (qui n'avait pas été fetched) et indication cours de Laurence français et anglais possible
> Stages (refait lien) et cours (UK)

- cours/index.html
>  Update index cours / UK

- cours/index.html
Cours barré et ajout en rouge du mot annulé
> Annulation cours mardi 16h30 dans \cours\index

- _includes/enseignantes/ora.html
- cours/dates_meditation.html
Suppression de la phrase en doublon dans la présentation d'Ora Correction de l'année 2022-2022 en 2022-2023 dans le fichier des dates de méditation
> Enseignant-Ora et médit

- _config.yml
- _includes/head.html
- Add `<meta name="keywords" content="cours, yoga, grenoble">`.
> SEO : rajout de mots clés pour améliorer le référencement.

- stages.html
> StagePerinee1Complet

- cours/index.html
- stages.html
Dans stages.html : indication stage passé pour celui du 03/12/22 
Dans Cours\index  :
- suppression début des cours le 19/09
- suppression du cours éveil matinal
> Cours_eveil_stage_passe

- stages.html
1ères modifs indiquées par Maya (hors changement couleurs)
> Stages_Maya_01

- cours/index.html
Simplification du texte relatif aux cours d'essai
> Cours_essais_modifs_Maya

- _sass/v1/_variables.scss
Eclaircissement du fond violet
> Couleur fond titre stages

- index.html
CENTRE VIE EN YOGA en majuscules sur téléphones
Modification de la phrase de la page d'accueil selon avis Maya
> Accueil_Maya

- _includes/enseignantes/ora.html
> Enseignante Maya

- cours/contenu.html
- cours/dates_cours_essai.html
- cours/dates_meditation.html
- cours/dates_vacances.html
- cours/index.html
- cours/tarifs.html
Index : simplification de la phrase pour idée cadeau
Contenu : déplacement de vidéos avant les audios
Cours d'essai : suppression de la première information
Méditation : ajout de avec Ora
Dates vacances : ajout de l'indication de la période de cours et du fait qu'ils n'ont pas lieu pendant les vacances
Tarifs : Fond dans les cellules + écriture en gras. Les avertissements sont déplacés à la fin
> Cours Maya

- _config.yml
Ajout de stages dans les mots clés
Modification du descriptif, trop long et ne s'affichant pas (limité à 150 caractères ?)
> MAJ mots clés

- cours/dates_cours_essai.html
- cours/dates_meditation.html
- cours/dates_vacances.html
Suppression du sous-menu cours d'essai
> SousMenu cours d'essai

- stages.html
Ajout de la mention Passé aux stages des 10/12/22 et 21/01/23
> Stages passés

- index.html
Ajout du nom du photographe pour la photo d'Eva
> Diaporama Eva

- bibliotheque.html
> Bibliotheque

- yoga.html
Changement du numéro d'ordre.
Ajout de photos
> AProposDuYoga

- _includes/enseignantes/eva.html
- _includes/enseignantes/ora.html
- _includes/enseignantes/yannick.html
- enseignantes.html
Changement du numéro d'ordre.
Ajout de photos à la fin pour Ora, Eva et Yannick.
> Enseignantes

- cours/contenu.html
- cours/dates_meditation.html
- cours/dates_vacances.html
- cours/douceur.html
- cours/maternite.html
- cours/particuliers.html
- cours/video_audio.html
Réduction du sous-me contenu.
Ajouts des sous-menus : cours particulier, maternité et yoga douceur. Renumérotation des sous-menu dates...
> Ajout de sous-menus

- contact.html
Réorganisation de l'ordre des informations selon message d'Ora du 05/02/23
> Maj Contact

- cours/dates_cours_essai.html
Suppression des lignes intempestives résultats de la récupération de Marc (je suppose).
> Essais_maj

- cours/douceur.html
Suppression de la dernière photo d'Ora en double
> MAJ douceur

- cours/video_audio.html
Enlever les réflexions sur les textes de Yoga du bas de l'onglet vidéos et audios à la demande de Maya. Cela fait double emploi...
> Videos_Audios

- cours/douceur.html
Mise en gras des textes en noir.
Ajout d'une vidéo
> Yoga douceur viseo

- stages.html
Ajout d'une présentation des stages d'été
> Stages_ete

- _includes/footer.html
> Facebook_Instagram

- index.html
Diminution de la marge sous le texte Vie en Yoga sur smartphone
> Marge_sup_smart_

- _includes/footer.html
Remplacement du texte 30 ans ... par les liens présentés par une phrase.
> Footer facebook

- _includes/footer.html
- index.html
Remise en ordre suite à incompréhension
Correction Instagram
> Photos-Facebook

- index.html
This reverts commit 9a92e4ba694d1a65c3b8fce01c73646d0f5eb934.
> Revert "Ordre diapo démarrage"

- _includes/footer.html
> Texte rejoignez nous

- index.html
Rend la première diapo active en premier.
(corrige l'erreur faite en déplaçant simplement les deux blocs initiaux en 8ème position)
> Carousel_ordre

- _includes/footer.html
Ajout d'un retour chariot après les deux points
(sur certains portable la césure se fait après le logo facebook). Il faudra ultérieurement ne faire cet ajout que pour les portables.
> Footer_retour charriot

- _includes/header.html
- cours/index.html
- cours/maternite.html
- cours/tarifs.html
- index.html
Modification des titres
Remplacement de certains textes
> Titre des menus et sous-menus

- cours/contenu.html
Les textes ont été intégralement revus par Maya afin de mieux comporter de mots clés.
> Revision du contenu d'un cours

- cours/contenu.html
> Contenu_photos

- _sass/v1/_base.scss
- index.html
Modification du titre
Révision des nuances de blanc du pied de page
> TitreEtFooter

- cours/contenu.html
Modification texte et emplacement de la première photo
> MAJ Contenu

- cours/particuliers.html
Modifications et ajouts dans le texte par Maya.
> MAJ Cours particuliers

- _includes/enseignantes/eva.html
- _includes/enseignantes/laurence.html
- _includes/enseignantes/ora.html
- _includes/enseignantes/yannick.html
Ajouts de liens en relation avec EFYARA, FNEY, TATSKY, BOHLE ANGOT
> Enseignantes_liens

- stages.html
Ajout de la mention passée pour les stages périnée 3
> Stages_MAJ

- stages.html
Ajouts des mots de passe fournis par Maya le 28/03
> Stages_MdP

- stages.html
Mise à jour de la page stages avec toutes les indications sur la page et une seule fiche d'inscription pour tous les stages. Photos ajoutées
> MAJ stages version Maya

- _config.yml
Modification des mots clés généraux
> MotsClefs_config

- cours/index.html
Ajouts de mots clés spécifiques pour la page planning des cours collectifs
> MotsClefs_planning_cours

- cours/tarifs.html
Ajouts de mots clefs spécifiques à la page tarifs des cours
> MotsClefs_tarifs

- cours/contenu.html
Ajouts de mots clef spécifique à la page contenu d'un cours
> MotsClefs_contenu_cours

- cours/particuliers.html
Ajout de mots clés spécifiques à la page cours particuliers
> MotsClef_Particuliers

- stages.html
Rectificatif de l'horaire de fin
> Stage_douceur

- stages.html
Modification du texte sur le rabais de 10%
> Stages_cadeau

- stages.html
Modification du titre de la page Stages
> Titre_Stages

- cours/maternite.html
- cours/particuliers.html
Inversion de l'ordre dans sous-menu avec cours particulier Ajout de mots clés spécifiques
> Yoga_prenatal

- stages.html
Ajout de l'après-midi du 17 juin
> Stage_17juin

- index.html
Mise à 75% des photos du diaporama
> Diaporama75

- index.html
> Diaporama mixte75_100

- _sass/v1/_base.scss
Ajout des classes couleur des nouveaux enseignants
> Classes Couleurs

- _sass/v1/_base.scss
Ajout de la couleur meditation
> Classe couleur 2

- _includes/enseignantes/elke.html
Modification de la présentation d'Elke
> Presentation Elke

- index.html
> Diaporama2023-24

- enseignantes.html
Mise à jour de enseignantes.html avec les nouveaux enseignants pour 2023-2024
> MAJ enseignantes

- cours/dates_cours_essai.html
- cours/index.html
Mise à jour des fichiers index et dates_cours_essai pour 2023-2024
> MAJ Cours et cours d'essai 2023-2024

- cours/dates_meditation.html
- cours/dates_vacances.html
- cours/tarifs.html
Mise à jour des tarifs pour 2023-2024
et des dates des méditations et des vacances
> MAJ tarifs et dates

- cours/tarifs.html
Correction du titre 2023-2024 au lieu de 2022-2023
> MAJ tarifs

- _includes/enseignantes/sophie.html
Correction de sa présentation mise à kjour par Maya et Daniel
> MAJ Sophie

- index.html
Ajout du lien et de la mention de gratuité
> Essais diaporama

- yoga.html
Suppression d'une ligne oubliée
> Correction yoga

- cours/video_audio.html
> Videos_Eva

- _includes/enseignantes/ora.html
Remplacement du lien pour la FNEY.
> Ora et FNEY

- _includes/enseignantes/jenny.html
- _includes/enseignantes/sebastien.html
- _includes/enseignantes/sophie.html
Ajout d'un lien sur le mot "enseigne" pour Sébastien, Jenny et Sophie (facebook)
> Liens_Internet_enseignants

- _includes/enseignantes/delphine.html
Ajout d'un lien sur le site de Delphine
> MAJ Delphine

- cours/index.html
Ajout de la mention "hors vacances scolaires" à la période des cours
> PériodeDesCours

- stages.html
Suppression du stage de Méaudre, déjà passé
> Stage_meaudre

- _includes/header.html
- contact.html
- mediatheque/bibliotheque.html
- mediatheque/video_audio.html
Restructuration du menu :
- à gauche, cours type subpage
- pages de type page
- sous-menu mediatheque de type sub-mediatheque
- pages de type pages-a-droite-de-mediatheque
> Mediatheque et menu general

- cours/reglement_cond_tarifs.html
> Lien reglement

- _config.yml
- cours/contenu.html
- cours/index.html
- cours/maternite.html
- cours/particuliers.html
- cours/tarifs.html
This reverts commit 60c10bd3707f8fcc09d64ca2ae760e3ea14c6305.
> Revert "MAJ mots clés"

- stages.html
Mise à jour des stages pour 2023-2024
> Stages 2023_24

- cours/dates_cours_essai.html
- cours/index.html
Suppressions de la semaine d'essais
> Fin semaine essais

- index.html
> MAJ page entree

- stages.html
Correction numérotation stages stress-sérénité
Suppression du mot description pour stages d'été
> MAJ stages.html

- stages.html
Ajout du 16 décembre pour stage Yoga et Voix.
Mise en majuscule des titre pour les stages d'été
> MAJ Stages

- stages.html
> MAJ_Stage_12h14h

- cours/dates_meditation.html
Remplacement de la date de novembre
> MAJ méditation

- _includes/enseignantes/mariajose.html
> MAJ Mariajose

- cours/index.html
Suppression Jenny pour tel vertical
> MAJ Cours 2023

- _sass/v1/_base.scss
- cours/contenu.html
- cours/cours_2024_2025.html
- cours/dates_cours_essai.html
- cours/dates_meditation.html
- cours/dates_vacances.html
- cours/douceur.html
- cours/maternite.html
- cours/particuliers.html
- cours/reglement_cond_tarifs.html
- cours/tarifs.html
Ajout du planning des cours 2024-2025 et des cours d'essai.
> Cours et essais 2024-2025

- yoga.html
Ajout des enseignantes Maria et Margot
> MAJ _Styles

- cours/cours_2024_2025.html
- cours/index.html
> Cours d'été

- cours/reglement_cond_tarifs.html
> MAJ reglement

- cours/cours_2024_2025.html
- cours/index.html
Ajout des cours d'été de Sophie
> MAJ Sophie cours été

- cours/reglement_cond_tarifs.html
- stages.html
Ajout des conditions d'annulation aux stages d'été
> Annulation_stage_dEte

- cours/dates_meditation.html
Mise à jour des dates des séances de méditation 2024-2025
> MAJ meditations

- cours/dates_cours_ete.html
- cours/index.html
Suppression des cours dans cours 2024-2025
Ajout d'un sous-menu Planning des cours d'été
> Ajout sous-menu cours été

- cours/dates_cours_ete.html
Vérif car ruby a détecté une erreur ???
> Ctrl Cours d'été

- cours/dates_cours_ete.html
> MAJ cours d'été

- cours/index.html
- index.html
Suppression de la réduction pour inscription en juin
> MAJ réduction

- stages.html
Suppression du stage de Méaudre
> MAJ_Stages

- cours/dates_vacances.html
- cours/douceur.html
- enseignantes.html
- yoga.html
Mise à jour selon instructions Maya du 4 juillet.
> MAJ Maya 04/07

- cours/index.html
Correction de l'horaire du cours de Margot du vendredi 10h45-12h00
> Cours_correction

- stages.html
Correction de l'erreur de date
> Rectificatif stage avril

- cours/tarifs.html
Ajouts des tarifs pour 2ème cours
> MAJ_tarifs

- cours/dates_cours_essai.html
- cours/index.html
- index.html
Suppression des infos relatives à la semaine de cours d'essai
> MAJ essais

- cours/tarifs.html
- index.html
Suppression indication journée portes ouvertes.
Ajout tarifs 2 cours étudiant
> MAJ tarifs+JOP

- cours/index.html
Modification du type de cours du vendredi 10h45
> MAJ vernd 10h45

- cours/index.html
Correction de l'horaire yoga douceur du vendredi : fin = 11h45
> MAJ horaire Yoga douceur

- mediatheque/bibliotheque.html
> MAJ bibliotheque

- mediatheque/bibliotheque.html
> MAJ_biblio

- cours/dates_cours_hiver.html
Indication des cours durant les vacances d'hiver 2025
> MAJ_cours_vacances_d_hiver

- cours/dates_cours_hiver.html
> Verif erreur ruby

- cours/dates_cours_avril.html
Ajout des cours donnés durant les vacances de Pâques
> Cours_Paques

- cours/dates_cours_avril.html
Ajout du cours d'Ora pendant les vacances d'avril
> MAJ cous avril

- cours/tarifs.html
Mise à jour des tarifs de l'année prochaine
> MAJ_tarifs2025-26

- cours/dates_vacances.html
MAJ des dates des vacances 2025-2026
> MAJ_dates_vac

- yoga.html
Mise à jour des styles de yoga
> MAJ_styles

- cours/dates_vacances.html
Ajout pont de l'Ascension 2026
> MAJ dates vacances

- stages.html
Ajout des détails des stages de Sophie et Margot
> MAJ Sophie Margot

- stages.html
> MAJpassage

- cours/dates_cours_essai.html
- index.html
- stages.html
> MAJ cours dessai
